version: '3'

services:
  player-api:
    build:
      dockerfile: Dockerfile
      context: .
    command: ["npm", "start"]
    container_name: "player-api"
    depends_on:
      - mongodb
    env_file:
      - ./.env
    environment:
      - MONGO_URI=$MONGO_URI
      - NODE_ENV=$NODE_ENV
      - S3_BUCKET=$S3_BUCKET
      - S3_PUBLIC_KEY=$S3_PUBLIC_KEY
      - S3_SECRET_KEY=$S3_SECRET_KEY
      - S3_KEY=$S3_KEY
    ports:
      - "3030:3030"
    restart: unless-stopped
    volumes:
      - api_node_modules:/app/node_modules
      - .:/app

  mongodb:
    image: mongo
    container_name: "mongodb"
    env_file:
      - ./.env
    ports:
      - "27017-27019:27017-27019"
    restart: unless-stopped
    volumes:
      - data-mongodb:/data/db

volumes:
  data-mongodb:
  api_node_modules:
